### ISSUE TITLE
Entrega-Frontend-Sprint2-Proyecto

### ISSUE THREAD

**Issue by Gladiiadorcibernetico** [academia-geek/frontend-sprint-2-Gladiiadorcibernetico#1]
Se creo la maquetación.  Se creo la transición entre contenedores con componentes de clase. se procedió a crear un datalocal y a desarrollar el registro y el login, mediante componentes de funciones. 

Todo lo trabajado, esta en una misma carpeta. Hoy al querer desplegar la app, utilice unos comandos force, ya que no se sucedían los cambios que querían, y termine borrando el proyecto tanto del repositorio de la academia como de la carpeta local de mi computador. Logre recuperarlo. Igualmente había trabajado todo en una misma carpeta.

En las imágenes adjuntas del wakatime aparecen dos carpetas diferentes, ya que el proyecto lo comencé a desarrollar en una carpeta x, y luego al recordar que había que trabajarla en la del repositorio clonado, hice la migración.

Defensa del sprint:  https://www.youtube.com/watch?v=uPIKZAcTnv8

wakatime 
![waka1](https://user-images.githubusercontent.com/96251142/182589018-3656da07-6597-4555-9f6e-63f8e6124613.png)
![waka2](https://user-images.githubusercontent.com/96251142/182590164-2092de5b-04f9-43b0-a6bb-dd594a88fefd.png)

**Comment by leonyudithk** [comment]
@Gladiiadorcibernetico  espero que se encuentre bien. recomendación crear un issues por cada entrega (reto1 un issues, reto 2 issues y proyecto otro issues).

Reto 1: Cumple  con todos los requerimientos básicos solicitados
Reto 2:  Cumple con los requerimientos básicos solicitados.
Proyecto final: El proyecto cumple con todos los requerimientos solicitados, se evidencia gran parte de la funcionabilidad de todo el proyecto final, debe reforzar react, react-hooks. Feliz día. Buen trabajo. 

Posdata: Por favor recordar que todos los sprint se sustentan. y agendar para el sprint 3.
